In [2]:
import pandas as pd
df=pd.read_csv("../data/clean_reviews.csv")
df.head()

                                              review sentiment
0  This desk lamp has both good and bad points, o...   Neutral
1  The smartwatch exceeded my expectations, aweso...  Positive
2  Really top-notch bluetooth speaker, exactly as...  Positive
3  Shipping took a while but the laptop backpack ...  Positive
4  FAST SHIPPING, HOWEVER THE SMARTWATCH ITSELF I...  Negative

In [3]:
df["review"].head(10).tolist()

["This desk lamp has both good and bad points, overall it's fine for daily use.",
 'The smartwatch exceeded my expectations, awesome build quality and works perfectly :',
 'Really top-notch bluetooth speaker, exactly as described on the website. Fast delivery too.',
 'Shipping took a while but the laptop backpack itself is fantastic, no complaints on quality.',
 "FAST SHIPPING, HOWEVER THE SMARTWATCH ITSELF IS DEFECTIVE, PACKAGING COULDN'T SAVE IT.",
 'I have mixed feelings about this smartwatch, some features are good others are nothing special.',
 'the gaming mouse feels poor and cheap, definitely not worth the price tag. ðŸ˜¡    ',
 "Fast shipping, however the yoga mat itself is faulty, packaging couldn't save it.",
 "The office chair isn't bad, isn't great eitehr, just decent like most in this price range.",
 'This water bottle is amazing, customer support was also super helpful when I had a question.']

In [4]:
import re
def light_clean(text):
    text =str(text)
    text = re.sub(r"<.*?>"," ",text)
    text = re.sub(r"https?://\S+|www\.\S+"," ",text)
    text = re.sub(r"\s+"," ",text).strip()
    return text

In [5]:
light_clean(df["review"].iloc[0])

"This desk lamp has both good and bad points, overall it's fine for daily use."

In [6]:
df["clean_review"] = df["review"].apply(light_clean)

In [7]:
df[["review", "clean_review"]].head(10)

,review,clean_review
0,"This desk lamp has both good and bad points, o...","This desk lamp has both good and bad points, o..."
1,"The smartwatch exceeded my expectations, aweso...","The smartwatch exceeded my expectations, aweso..."
2,"Really top-notch bluetooth speaker, exactly as...","Really top-notch bluetooth speaker, exactly as..."
3,Shipping took a while but the laptop backpack ...,Shipping took a while but the laptop backpack ...
4,"FAST SHIPPING, HOWEVER THE SMARTWATCH ITSELF I...","FAST SHIPPING, HOWEVER THE SMARTWATCH ITSELF I..."
5,"I have mixed feelings about this smartwatch, s...","I have mixed feelings about this smartwatch, s..."
6,"the gaming mouse feels poor and cheap, definit...","the gaming mouse feels poor and cheap, definit..."
7,"Fast shipping, however the yoga mat itself is ...","Fast shipping, however the yoga mat itself is ..."
8,"The office chair isn't bad, isn't great eitehr...","The office chair isn't bad, isn't great eitehr..."
9,"This water bottle is amazing, customer support...","This water bottle is amazing, customer support..."

In [8]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

c:\Users\My Dell\OneDrive\Documents\opinionAI\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\My Dell\OneDrive\Documents\opinionAI\venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\My Dell\.cache\huggingface\hub\models--distilbert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [9]:
sample = df["clean_review"].iloc[0]
tokens = tokenizer.tokenize(sample)
tokens

['this',
 'desk',
 'lamp',
 'has',
 'both',
 'good',
 'and',
 'bad',
 'points',
 ',',
 'overall',
 'it',
 "'",
 's',
 'fine',
 'for',
 'daily',
 'use',
 '.']

In [10]:
tokenizer(sample,return_tensors="pt")

{'input_ids': tensor([[  101,  2023,  4624, 10437,  2038,  2119,  2204,  1998,  2919,  2685,
          1010,  3452,  2009,  1005,  1055,  2986,  2005,  3679,  2224,  1012,
           102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [11]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df["label"] = label_encoder.fit_transform(df["sentiment"])

df[["sentiment", "label"]].head(10)

  sentiment  label
0   Neutral      1
1  Positive      2
2  Positive      2
3  Positive      2
4  Negative      0
5   Neutral      1
6  Negative      0
7  Negative      0
8   Neutral      1
9  Positive      2

In [12]:
label_encoder.classes_

array(['Negative', 'Neutral', 'Positive'], dtype=object)